# Configuration minimale pour tester
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gotk8s
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30100
        hostPort: 30100
      - containerPort: 30101
        hostPort: 30101
